application: revive-explorations
version: 1
runtime: python
api_version: 1
threadsafe: true

handlers:
- url: /(.*\.(gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css))

- url: /robots.txt
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg))

- url: .*
  script: main.py
